AwesomePrint.defaults={
  indent: 2,
  index: true,
  html: false,
  multiline: true,
  plain: false,
  raw: false,
  sort_keys: false,
  sort_vars: true,
  limit: false,
  ruby19_syntax: true,
  class_name: :class,
  object_id: true,
  color: {
    args: :pale,
    array: :white,
    bigdecimal: :blue,
    class: :yellow,
    data: :greenish,
    falseclass: :red,
    integer: :blue,
    float: :blue,
    hash: :pale,
    keyword: :cyan,
    method: :purpleish,
    nilclass: :red,
    rational: :blue,
    string: :yellowish,
    struct: :pale,
    symbol: :cyanish,
    time: :greenish,
    trueclasss: :green,
    variable: :cyanish
  }
}